version: "3.8"
  
services:
  app:
    build: ./app 
    container_name: reactapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      # - ./app/node_modules
    stdin_open: true
    tty: true
