version: '3'

services:

  mysql:
    build: ./database
    container_name: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: backend
      MYSQL_PASSWORD: helloworld
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - "3308:3306"

  go-api:
    build: 
      dockerfile: Dockerfile.dev
      #context: ./backend
    container_name: go-api
    ports:
    - 8081:8081
    volumes:
     - .:/app
    expose:
      - 8081
    depends_on:
      - mysql
    links:
      - mysql
    tty: true
